### ISSUE TITLE
Error with installing packages

### ISSUE THREAD

**Issue by samarth-wustl** [YttriLab/A-SOID#14]
Hi
I am trying to run A-Soid on some of my video datasets.
I am using a Windows 7 64 bit OS.

When installing the requirements, I get an error in installing hdbscan. When i force install it using conda, streamlit doesn't render and popup errors with numpy long.
![image](https://user-images.githubusercontent.com/110621754/223877108-2a95ccc2-083f-4037-9832-dd3943d8b5db.png)

**Comment by JensBlack** [comment]
Hi,

this might be a potential duplicate from this issue:
 #3 
 Can you try the proposed solution and report back if this solved your issue?
 
 Thanks!
