### ISSUE TITLE
unable to proceed without config file

### ISSUE THREAD

**Issue by zhenyuan992** [YttriLab/A-SOID#24]
i am trying to use asoid on the CALMS21 dataset
i have successfully converted the .json into .npy files, but i am unable to proceed.

i suspect that i need a config file, please provide guidance on how to obtain that.

thanks in advance! ps, I'm trying to use asoid for my dataset, but i don't have training labels yet.

![image](https://user-images.githubusercontent.com/12291964/233892456-3fdae835-4a3b-43cc-ba52-eb8708b34cdc.png)

![image](https://user-images.githubusercontent.com/12291964/233892409-9eb70d44-dc85-47a4-9280-5b02ca3b1fee.png)

![image](https://user-images.githubusercontent.com/12291964/233892248-a41edd9b-183f-4065-ba1c-b19dfd9a99b3.png)

**Comment by JensBlack** [comment]
Hi @zhenyuan992,

First, thanks for trying out A-SOiD and reaching out when you found an issue.

### Creating a new project results in a folder with a `config.ini` file

A-SOiD generates a project folder based on your input data (e.g., the CalM data) in the designated folder path:

![grafik](https://user-images.githubusercontent.com/44863941/233953855-9f1971f6-59de-44e6-9865-9045b27463d6.png)

So depending on your input, you should find the project (incl. the config file) there.

Unfortunately, the second step requires you to re-upload that created config file (it's an app thing), so go to the project folder and just drag and drop the config file (or click browse files) in the ``Upload Config File``.

![grafik](https://user-images.githubusercontent.com/44863941/233957250-e561dc89-4dfd-4897-ad2a-d02f9063ee2b.png)

### Example from one of my own projects:

When you start out with a project, the folder content looks like this:
![grafik](https://user-images.githubusercontent.com/44863941/233955136-9d273152-5828-4bd7-aa92-f39de8b8c46d.png)

But all files (e.g., feature extraction) will be added there.

The config file looks like this and is a collection of your input from the first step.
Some values can be changed directly in there (it's a text file, just open it with the editor), but most of the time it is better to recreate a project or change parameters from within the app.

![grafik](https://user-images.githubusercontent.com/44863941/233955660-3c88e896-eec9-4ee5-946a-4ea509124c61.png)

You can also view a config file after uploading in the app:

![grafik](https://user-images.githubusercontent.com/44863941/233956356-4f735d6d-40b1-4a8a-aa3d-80f39e682c56.png)

---

I think this should solve your issue (so I am closing it) but feel free to reopen it, if this did not solve it. If you are running into other issues, I ask you to open a different one.
