### ISSUE TITLE
ModuleNotFoundError: No module named 'hdbscan'

### ISSUE THREAD

**Issue by kapilsaxena33** [YttriLab/A-SOID#3]
Hi There,
I am frome Uni of Minnesota from Suhasa's lab (https://www.bsbrl.org/)
I got the pleasure to meet Jens at SFN 2022, that's when I felt that A- SOiD is awesome and i thought of trying it. I created a virtual environment in anaconda and running from there. 
i get"ModuleNotFoundError: No module named 'hdbscan'" error. Following this I did uninstall and installed the hdbscan, with no results.
Did you guys received the same. What is the solution, running on Windows 11, And in anaconda 

Traceback (most recent call last):
  File "C:\Users\kapil\.conda\envs\asoid\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 557, in _run_script
    exec(code, module.__dict__)
  File "asoid\app.py", line 12, in <module>
    import apps as _stable_apps
  File "asoid\apps\__init__.py", line 1, in <module>
    from . import A_data_preprocess, B_extract_features, C_auto_active_learning, E_predict, F_view,\
  File "asoid\apps\G_unsupervised_discovery.py", line 5, in <module>
    from utils.unsupervised_discovery import Explorer
  File "asoid\utils\unsupervised_discovery.py", line 13, in <module>
    import hdbscan
ModuleNotFoundError: No module named 'hdbscan'

**Comment by JensBlack** [comment]
Hi!

Great that you like A-SOiD and thank you for visiting me at SfN. This presumably looks like a simple issue to fix but to be sure, let's iterate through some safety questions here:

TL&DR: `pip install hdbscan` should have done the trick...

1. Which file did you use to install A-SOid (and the environment)?

The YAML file does not contain hdbscan as a module, but the requirements.txt does.
So did you install the environment from the YAML but did not use setup.py?

If so try installing the A-SOiD package using `pip install .` in the repo folder (where setup.py is).
Is hdbscan installed correctly?

2. Could you please post the results of `conda list` here, so we can verify that hdbscan was in fact not installed?

3. Could you please create a new environment and repeat the installation steps to see whether there are any installation issues?

Thank you for reporting this issue! I hope we can solve your issue ASAP.

**Comment by kapilsaxena33** [comment]
Thanks for the explanation,
Should have follow your installation sequence. 

Pip install did not worked, it worked then it says the hbdscan not installed. 

I solved it by doing the following

conda install -c conda-forge hdbscan

it did installed the hdbscan also give this output The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2022.12.~ --> pkgs/main::ca-certificates-2022.10.11-haa95532_0
  certifi            conda-forge/noarch::certifi-2022.12.7~ --> pkgs/main/win-64::certifi-2022.9.24-py38haa95532_0
Proceed ([y]/n)? n
I  declined all of the changes offered
then it worked
thanks for the quick reply. 

Yes, I like to work in and anaconda environment, so followed the guide that suggested to create the environment.  and got the above error.  First instance it does launched the app but after that it keeps on giving this error.
Followed the other method of installation as well, just copy and paste the commands specified in your instructions (https://github.com/YttriLab/A-SOID) 
when tried to launch the app it give an error

(base) C:\Users\kapil>asoid app
'asoid' is not recognized as an internal or external command,
operable program or batch file.
is there is anything that i am missing.

thanks for the help. 
I really appriciate.

**Comment by JensBlack** [comment]
Great that you found a solution.
I cannot replicate your error during installation though on my machines. It would be great if you could send me some details (like the output of `conda list` and the version of `python` that you are installing with).

---
> (base) C:\Users\kapil>asoid app
'asoid' is not recognized as an internal or external command,
operable program or batch file.
is there is anything that i am missing.

This is a result of you not installing with `pip install .` through setup.py.
If you are following this instructions, you need to start A-SOiD by going to the directory you cloned it into and then use:

````
streamlit run asoid/app.py
````

I will close this issue as it is solved.
