### ISSUE TITLE
TypeError when starting the A-SOID app

### ISSUE THREAD

**Issue by islaxiao01** [YttriLab/A-SOID#45]
Hi there, 
I'm running into a typeerror when trying to start the app (after inputting the command "asoid app"). The bug is as follows: TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'builtin_function_or_method'. However, my hdbscan installation seemed successful, and everything is find until I tried starting the app. The line before the error message is:  FAST_METRICS = KDTree.valid_metrics + BallTree.valid_metrics + ["cosine", "arccos"].
Please let me know what went wrong, if possible.
<img width="661" alt="Screenshot 2023-06-30 151542" src="https://github.com/YttriLab/A-SOID/assets/115672646/5015b772-4c04-4c32-a4ff-103d482fe575">

**Comment by JensBlack** [comment]
I've forwarded this to the one and only @runninghsus . He is the UMAP/HDBscan wizard and should be able to help. In the mean time, could you please provide some additional info.

A-SOiD version, your system (Mac, Windows, etc.), and if you were previously successful in starting the app.
