### ISSUE TITLE
streamlit fails to run

### ISSUE THREAD

**Issue by mauricev** [YttriLab/A-SOID#54]
On Windows 11, we installed a-soid. The installation proceeded uneventfully, unlike the Silicon Mac with Sonoma. However, when we run it, we get this error

```
Error: StreamLit requires raw Python (.py) files, but the provided file has no extension.
```

**Comment by JensBlack** [comment]
Hi Mauricev,

thanks for reporting this installation issue. This might be a path issue of the `asoid app` command.

1. Can you give me more information on the steps you took before calling the app?

Here is an example how to do this normally:
 ````
(base) C:\Users\JSchw>activate asoid

(asoid) C:\Users\JSchw>asoid app

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.26.33.62:8501

````

2. Can you move to the installation folder and run asoid by calling `streamlit run asoid/app,py`

This is the alternative directly with streamlit:

1. Go to your local git clone of asoid
````
(base) C:\Users\JSchw\PycharmProjects\A-SOID>activate asoid
````
2. Run asoid with:
````
(asoid) C:\Users\JSchw\PycharmProjects\A-SOID> streamlit run asoid/app.py
````

Let me know if this helps!

**Comment by JensBlack** [comment]
closing as stale. feel free to open again

**Comment by arjunsur12** [comment]
Had the same issue, the alternative to run with streamlit (steps 1 and 2 at the bottom) worked. Thank you!
