### ISSUE TITLE
PROJECTION CREATION: TypeError: '>' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by DavidGill159** [YttriLab/A-SOID#57]
**Description**
Tried creating the project after successfully uploading DLC and annotated data and this error was returned. 

**Desktop:**
 - OS: Windows 10
 - Browser chrome

![image](https://github.com/YttriLab/A-SOID/assets/116177739/e01ffad6-20d1-4aad-8822-49de536397d6)

**Comment by DavidGill159** [comment]
Solution: Boris outputted events need to be exported as a [binary table](file:///Z:/Lab%20Tech/David%20Research/A-SOiD/Boris%20Tutorial%20Docs.html#:~:text=Export%20events%20as%20Behaviors%20Binary%20Table%C2%B6)

**Comment by JensBlack** [comment]
Thank you for sharing the issue and the solution!
