### ISSUE TITLE
'hide_index' error message when predicting behaviors

### ISSUE THREAD

**Issue by pozel** [YttriLab/A-SOID#61]
**Describe the bug**
I am able to successfully save the annotated ethogram csv under the "predict" tab of the app. However, I see the below error message.  I'm not sure if the error message is detrimental to the analyses, however it would help to understand what happened. Has anyone experienced this before and might give some light into what the problem is?

`TypeError: DataFrameSelectorMixin.dataframe() got an unexpected keyword argument 'hide_index'
Traceback:
File "C:\Users\pozel\Anaconda3\envs\asoid\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "C:\A-SOID\asoid\app.py", line 317, in <module>
    main()
File "C:\A-SOID\asoid\app.py", line 306, in main
    F_predict.main(ri=ri, config=st.session_state['config'])
File "c:\a-soid\asoid\apps\F_predict.py", line 746, in main
    describe_labels_single(single_label, annotation_classes_ex, framerate, summary_col)
File "c:\a-soid\asoid\apps\F_predict.py", line 621, in describe_labels_single
    placeholder.dataframe(count_df, hide_index=True)
File "C:\Users\pozel\Anaconda3\envs\asoid\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)`

**Screenshots**
![error2](https://github.com/YttriLab/A-SOID/assets/67648249/7a9aa8fe-02d0-4254-8c52-4bb1db9b1f7e)

**Comment by JensBlack** [comment]
From your screenshot I gather that you are only getting about half of what should be shown in `predict` tab.

However, the error indicates that there is something wrong with streamlit.

This might be a version issue. Can you send me the output of `conda list` in your asoid environment? This will give me an overview of which versions you are using.

Some Background info:

The function is clearly documented in streamlit [Documentation](https://docs.streamlit.io/library/advanced-features/dataframes#stdataframe-ui-features)
Here is a discussion on a previous issue on streamlit [Issue](https://discuss.streamlit.io/t/hide-row-indices-when-displaying-a-dataframe-in-streamlit-v1-16-0/35296/9)

**Comment by pozel** [comment]
Sure thing! Thank you for linking the documentation from streamlit. I'm adding my environment here in a txt file.
[asoid_env.txt](https://github.com/YttriLab/A-SOID/files/13720726/asoid_env.txt)

**Comment by JensBlack** [comment]
Seems like you have an older version of streamlit installed:

> streamlit                 1.20.0                   pypi_0    pypi

Can you try to update streamlit and see whether this error still persists?

You can update streamlit in the environment by using:

`pip install --upgrade streamlit`

Let me know if this works!

**Comment by pozel** [comment]
Thank you -- Works great!
