### ISSUE TITLE
WIN10 permission denied

### ISSUE THREAD

**Issue by kipkeller** [YttriLab/A-SOID#64]
**Describe the bug**
Just started on WINDOWS 10 with the CALms (task3) data and A-SOID cannot access the (npy) datafiles (permission denied - ERRNO 13)

**To Reproduce**
Just followed the DEMO instructions, steps 1-5 and the error occurs on step 5

**Expected behavior**
Expect the demo to continue by loading the data

**Screenshots**
![image](https://github.com/YttriLab/A-SOID/assets/32721880/c34b99e5-1908-4618-8cea-4d683a12e3fb)

**Desktop (please complete the following information):**
 - August 2023: A-SOiD v0.3.0
 - Windows 10.0.19045
 - Chrome 120.0.6099.200
 - (also tried with firefox 121.0.1)
 

**Project Config (please post the content of the corresponding config.ini file)**
used the Calms from paper (so did not specify a config file)

**Additional context**
permissions are granted in full according to WINDOWS

THANKS!

**Comment by kipkeller** [comment]
OK - now started from scratch, moved the data into a directory within the asoid directory and it works! Not sure what I did differently.
Besides the dos on github and the bioarchiv paper are there more clues on how to get going with it? About to try our own data with DLC and Boris. Thanks

**Comment by JensBlack** [comment]
Great that it worked out and thank you for reporting this back so other users benefit from your solution!

There is a GitPod workshop version I've been using to teach people how to do the basics:

https://github.com/JensBlack/A-SOID_workshop

> Disclaimer: This is not using the latest version and uses the CALMS21 data, so it is probably not what you are looking for.

If you need more detailed explanations, you are welcome to open a new issue/feature request with the specific questions, so it's findable for others as well.
