### ISSUE TITLE
Please train a iteration-0 model in Active Learning step.

### ISSUE THREAD

**Issue by Niels132** [YttriLab/A-SOID#68]
Dear A-SOiD Team,
Everytime I want A-SOiD to predict new datasets (deeplabcut pose files) I get the error "Please train a iteration-0 model in Active Learning step.". However I did the active learning and also get the notification "This prefix had been classified.". In the iteration-0 folder there is both an iter0 and the iterX.sav file. I do not know where the error originates from. I tried on three different devices and alway get the error.

I used deeplabcut pose data and boris binary annotated files. I had to use .04 resolution for boris files becuase the frame rate was 25 and the boris data with suggested 10Hz have not been a multiple of that. I thoufght this would be no problem since I was able to specify this in the GUI.

Config
![grafik](https://github.com/YttriLab/A-SOID/assets/122016920/a25ecf50-f69c-47c2-aba7-4f5c14ca5bc3)

Extract Features
![grafik](https://github.com/YttriLab/A-SOID/assets/122016920/54616528-ab39-4925-b0df-b8da64d756c5)

Active learning
![grafik](https://github.com/YttriLab/A-SOID/assets/122016920/050a7822-4158-4f74-b7ad-46fbc1057d6b)

I skipped refine behavior

Prediction
![grafik](https://github.com/YttriLab/A-SOID/assets/122016920/afd39658-6046-462b-b4cb-fc85c69aee27)

I would really love to know what went wrong and how this could be fixed. I think from reading the paper this is a great tool, that I would really profit from.
Best wishes 
Niels Röhrdanz

**Comment by JensBlack** [comment]
Hi Niels,

thank you for reporting your issue. It seems that everything worked fine until the very last step. I understand that this error message does not provide enough information to solve this issue on your side. I will investigate this in the code.

It would be great if you could also send me your console output prior to the error, as our try/except loop caught an error but gave you that message instead.

---

 In the meantime, I have some initial solutions that might help in this case: 
 
 Have you tried to remove the config file from the upload and reuploaded it again? Sometimes Streamlit (the GUI platform we use) needs a little reminder to refresh. 
 
 An alternative to this is to close A-SOiD and open it again. Then upload the config and go directly to the prediction step. Streamlit has had issues with caching in the past and this will resolve them.
 
let me know if this works out.

**Comment by Niels132** [comment]
Hi Jens,
I tried out closing and reopening, reloading and directly opening the config file. I still get the same result. As console output I get a empty line. 
I will try out the suggested dataset on the github page and try if this works.
![grafik](https://github.com/YttriLab/A-SOID/assets/122016920/28377f24-d080-4507-aa2a-16364acb4cb7)
this is what the iteration-0 folder looks like right now, maybe you can see something suspicious there from looking on file sizes.
Best wishes and thanks already, I keep you updated whether I get it working on the [CalMS21](https://data.caltech.edu/records/s0vdx-0k302)
Niels

**Comment by JensBlack** [comment]
Can you do me the favor and delete the iter0 and iterX files, then rerun the active learning step?

After that, you should see the following when going to the predict tab:

<img width="1512" alt="Screenshot 2024-02-28 at 09 20 48" src="https://github.com/YttriLab/A-SOID/assets/44863941/9e4b02ad-f886-4f49-bf5e-5c7d7600f80d">

The blue info box on the top right indicates if the model was loaded. Is this the case for you?

then following the upload of new data:

<img width="1162" alt="Screenshot 2024-02-28 at 09 27 28" src="https://github.com/YttriLab/A-SOID/assets/44863941/68bc9783-8da1-48bd-8d89-111138b70697">

**Comment by JensBlack** [comment]
I uploaded a hotfix that should fix the issue. Can you install the new version and confirm this with me? 
> I haven't created a release tag for this yet, so just the laster version from GitHub please

**Comment by Niels132** [comment]
Great news, now it works.
Best wishes
Niels
