### ISSUE TITLE
'Key Error' in Refinement Step After the First Sample

### ISSUE THREAD

**Issue by eacrummy** [YttriLab/A-SOID#84]
**Describe the bug**
Key Error for Behaviors('Other', 'Platform Time') when trying to look at video segments to refine labels.

**To Reproduce**
1. Go to Refine Behaviors
2. Update Refinements
3. Scroll down to selector for samples 0,1,2,3,4 (etc.)
4. See error following sample 0

**Expected behavior**
Expected to be able to select samples 0-4 (based on number of samples to refine at 5) and see different video clips of example behavior to edit behavioral classification at those timepoints.

**Screenshots**

![image](https://github.com/YttriLab/A-SOID/assets/54378695/e0f8dc3e-04ab-4453-95d5-436b5dc385b6)
![image](https://github.com/YttriLab/A-SOID/assets/54378695/adb24af5-f877-4a60-b40e-1fc0d71b2e1f)
![image](https://github.com/YttriLab/A-SOID/assets/54378695/517b502c-fd22-4dc8-a3e4-fe1b9c6a5718)
![image](https://github.com/YttriLab/A-SOID/assets/54378695/900f8e9b-c246-402c-aa22-468dbfa05da3)
![image](https://github.com/YttriLab/A-SOID/assets/54378695/67ca3b7b-88e7-4013-b917-705fe8268708)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome

**Project Config (please post the content of the corresponding config.ini file)**

![image](https://github.com/YttriLab/A-SOID/assets/54378695/6c7d8f13-30d9-4efb-bd6b-45c87969ea56)

**Additional context**

**Comment by JensBlack** [comment]
Thank you @eacrummy for reporting this issue.

I'll investigate this on my side, but it would be great to get some additional information:

1. Is this the first time you are refining in this project?
2. Did refinement work for "Freezing"?
3. Did refinement work for sample 0 in "Platform Time"?
4. Did you save your refinement after refining sample 0 or any other sample?
6. Did the error occur when you switched between behaviors? E.g., between the tabs "Freezing" and "Platform Time"

**Comment by eacrummy** [comment]
Hi Jens,

1. Yes, this was my first attempt to refine with a new video uploaded to the project
2. Freezing wasn't detected in this video 
3., 4. Sample 0 seemed to work - I could edit the labels for each timepoint, but I didn't save it or other samples.
5. Yes, the error occurred for multiple behaviors I switched between. 

Thank you for your help!
-Elizabeth

**Comment by eacrummy** [comment]
Hi Jens,

Not sure if this would explain the error, but we realized that we had to modify our Boris score time bins to match the 15 fps framerate of our videos. We also have portions of the video that start prior to session start for our behavior, so we think that the sleap predictions are excluding those frames and misaligning the Boris and pose estimation files. 

Elizabeth

**Comment by JensBlack** [comment]
Hi @eacrummy ,

Thanks for your patience. Yes, this is likely the issue.

All exported BORIS files must have the same lenght (in time) as the pose estimation files. That means, that you need to export the binary table from the start of the "observation" (video), not the first behavior.

This should fix your issue, but please let me know if it did.

Feel free to close the issue.

**Comment by eacrummy** [comment]
Hi Jens,

Thank you! We did try to rebin the BORIS timestamps at to match the 15 fps of the videos, but had issues with matching the time. We're working on using larger timebins (.2s to be 5fps) to see if it fixes our issue.
