### ISSUE TITLE
Allowing "Likelihood value to filter" for pose files of 0.99

### ISSUE THREAD

**Issue by JHartig** [YttriLab/A-SOID#86]
Currently the maximum likelihood cutoff for pose files that one can use is 0.95.
For most solid DLC RCNNs one would like to use up until 0.99 as a cutoff

Can you implement that?

**Comment by JensBlack** [comment]
That is certainly an easy thing to implement. I will add this to our next update.

For now, you can change it yourself here:

```
asoid/utils/load_preprocess.py:332
                    self.llh_value = upload_container.number_input('Likelihood value to filter',
                                                                   min_value=0.05, max_value=0.95,
                                                                   value=0.1)

```

change to this:
```
asoid/utils/load_preprocess.py:332
                    self.llh_value = upload_container.number_input('Likelihood value to filter',
                                                                   min_value=0.05, max_value=0.99,
                                                                   value=0.1)
```

**Comment by JHartig** [comment]
Great! Another thing that I came across for figures: Is there an easy way to change the code so the figures that are modifiable via the plotly interface can be exported in vectorized form? Otherwise it will be difficult to further process anything and that would massively increase the plots' usability beyond screening etc. (speaking about actual publication readiness)
