### ISSUE TITLE
Failed building wheel for hdbscan

### ISSUE THREAD

**Issue by karinmcode** [YttriLab/A-SOID#9]
Hi,

I am trying to install A-SOID but get this error message. I appreciate your help.

(asoid) PS C:\Apps\A-SOID> pip install .
Processing c:\apps\a-soid
  Preparing metadata (setup.py) ... done
Collecting matplotlib
  Using cached matplotlib-3.6.2-cp38-cp38-win_amd64.whl (7.2 MB)
Collecting numpy
  Using cached numpy-1.24.1-cp38-cp38-win_amd64.whl (14.9 MB)
Collecting pandas
  Using cached pandas-1.5.2-cp38-cp38-win_amd64.whl (11.0 MB)
Collecting seaborn
  Using cached seaborn-0.12.2-py3-none-any.whl (293 kB)
Collecting streamlit~=1.11.0
  Using cached streamlit-1.11.1-py2.py3-none-any.whl (9.1 MB)
Collecting streamlit_option_menu
  Using cached streamlit_option_menu-0.3.2-py3-none-any.whl (712 kB)
Collecting hydralit
  Using cached hydralit-1.0.14-py3-none-any.whl
Collecting opencv-python
  Using cached opencv_python-4.7.0.68-cp37-abi3-win_amd64.whl (38.2 MB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting stqdm
  Using cached stqdm-0.0.5-py3-none-any.whl (11 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.2.0-cp38-cp38-win_amd64.whl (8.2 MB)
Collecting h5py
  Using cached h5py-3.7.0-cp38-cp38-win_amd64.whl (2.6 MB)
Collecting plotly
  Using cached plotly-5.11.0-py2.py3-none-any.whl (15.3 MB)
Collecting pillow
  Using cached Pillow-9.4.0-cp38-cp38-win_amd64.whl (2.5 MB)
Collecting joblib
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting scipy
  Using cached scipy-1.10.0-cp38-cp38-win_amd64.whl (42.2 MB)
Collecting ipython
  Using cached ipython-8.8.0-py3-none-any.whl (775 kB)
Collecting psutil
  Using cached psutil-5.9.4-cp36-abi3-win_amd64.whl (252 kB)
Collecting numba
  Using cached numba-0.56.4-cp38-cp38-win_amd64.whl (2.5 MB)
Collecting hdbscan
  Using cached hdbscan-0.8.29.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: setuptools in c:\users\km195\anaconda3\envs\asoid\lib\site-packages (from asoid==0.2.0) (65.6.3)
Collecting umap-learn
  Using cached umap_learn-0.5.3-py3-none-any.whl
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting moviepy
  Using cached moviepy-1.0.3-py3-none-any.whl
Collecting packaging>=14.1
  Using cached packaging-23.0-py3-none-any.whl (42 kB)
Collecting requests>=2.4
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting tornado>=5.0
  Using cached tornado-6.2-cp37-abi3-win_amd64.whl (425 kB)
Collecting watchdog
  Using cached watchdog-2.2.1-py3-none-win_amd64.whl (78 kB)
Collecting tzlocal>=1.1
  Using cached tzlocal-4.2-py3-none-any.whl (19 kB)
Collecting typing-extensions>=3.10.0.0
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting blinker>=1.0.0
  Using cached blinker-1.5-py2.py3-none-any.whl (12 kB)
Collecting attrs>=16.0.0
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Collecting pydeck>=0.1.dev5
  Using cached pydeck-0.8.0-py2.py3-none-any.whl (4.7 MB)
Collecting protobuf<4,>=3.12
  Using cached protobuf-3.20.3-cp38-cp38-win_amd64.whl (904 kB)
Collecting cachetools>=4.0
  Using cached cachetools-5.2.1-py3-none-any.whl (9.3 kB)
Collecting semver
  Using cached semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting altair>=3.2.0
  Using cached altair-4.2.0-py3-none-any.whl (812 kB)
Collecting gitpython!=3.1.19
  Using cached GitPython-3.1.30-py3-none-any.whl (184 kB)
Collecting rich>=10.11.0
  Using cached rich-13.0.1-py3-none-any.whl (238 kB)
Collecting pympler>=0.9
  Using cached Pympler-1.0.1-py3-none-any.whl (164 kB)
Collecting validators>=0.2
  Using cached validators-0.20.0-py3-none-any.whl
Collecting pyarrow>=4.0
  Using cached pyarrow-10.0.1-cp38-cp38-win_amd64.whl (20.3 MB)
Collecting importlib-metadata>=1.4
  Using cached importlib_metadata-6.0.0-py3-none-any.whl (21 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting pytz>=2020.1
  Using cached pytz-2022.7-py2.py3-none-any.whl (499 kB)
Collecting cython>=0.27
  Using cached Cython-0.29.33-py2.py3-none-any.whl (987 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting hydralit-components>=1.0.7
  Using cached hydralit_components-1.0.10-py3-none-any.whl
Collecting bokeh
  Using cached bokeh-3.0.3-py3-none-any.whl (16.5 MB)
Collecting compress-pickle
  Using cached compress_pickle-2.1.0-py3-none-any.whl (24 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting prompt-toolkit<3.1.0,>=3.0.11
  Using cached prompt_toolkit-3.0.36-py3-none-any.whl (386 kB)
Collecting matplotlib-inline
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting traitlets>=5
  Using cached traitlets-5.8.1-py3-none-any.whl (116 kB)
Collecting stack-data
  Using cached stack_data-0.6.2-py3-none-any.whl (24 kB)
Collecting pygments>=2.4.0
  Using cached Pygments-2.14.0-py3-none-any.whl (1.1 MB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting jedi>=0.16
  Using cached jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.38.0-py3-none-any.whl (965 kB)
Collecting contourpy>=1.0.1
  Using cached contourpy-1.0.6-cp38-cp38-win_amd64.whl (163 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.4-cp38-cp38-win_amd64.whl (55 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting proglog<=1.0.0
  Using cached proglog-0.1.10-py3-none-any.whl (6.1 kB)
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting imageio-ffmpeg>=0.2.0
  Using cached imageio_ffmpeg-0.4.8-py3-none-win_amd64.whl (22.6 MB)
Collecting imageio<3.0,>=2.5
  Using cached imageio-2.24.0-py3-none-any.whl (3.4 MB)
Collecting numpy
  Using cached numpy-1.23.5-cp38-cp38-win_amd64.whl (14.7 MB)
Collecting llvmlite<0.40,>=0.39.0dev0
  Using cached llvmlite-0.39.1-cp38-cp38-win_amd64.whl (23.2 MB)
Collecting tenacity>=6.2.0
  Using cached tenacity-8.1.0-py3-none-any.whl (23 kB)
Collecting pynndescent>=0.5
  Using cached pynndescent-0.5.8-py3-none-any.whl
Collecting entrypoints
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting toolz
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting jsonschema>=3.0
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Collecting gitdb<5,>=4.0.1
  Using cached gitdb-4.0.10-py3-none-any.whl (62 kB)
Collecting lxml
  Using cached lxml-4.9.2-cp38-cp38-win_amd64.whl (3.9 MB)
Collecting bs4
  Using cached bs4-0.0.1-py3-none-any.whl
Collecting zipp>=0.5
  Using cached zipp-3.11.0-py3-none-any.whl (6.6 kB)
Collecting parso<0.9.0,>=0.8.0
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\km195\anaconda3\envs\asoid\lib\site-packages (from requests>=2.4->streamlit~=1.11.0->asoid==0.2.0) (2022.12.7)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting backports.zoneinfo
  Using cached backports.zoneinfo-0.2.1-cp38-cp38-win_amd64.whl (38 kB)
Collecting pytz-deprecation-shim
  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting tzdata
  Using cached tzdata-2022.7-py2.py3-none-any.whl (340 kB)
Collecting xyzservices>=2021.09.1
  Using cached xyzservices-2022.9.0-py3-none-any.whl (55 kB)
Collecting PyYAML>=3.10
  Using cached PyYAML-6.0-cp38-cp38-win_amd64.whl (155 kB)
Collecting asttokens>=2.1.0
  Using cached asttokens-2.2.1-py2.py3-none-any.whl (26 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting executing>=1.2.0
  Using cached executing-1.2.0-py2.py3-none-any.whl (24 kB)
Collecting smmap<6,>=3.0.1
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp38-cp38-win_amd64.whl (17 kB)
Collecting importlib-resources>=1.4.0
  Using cached importlib_resources-5.10.2-py3-none-any.whl (34 kB)
Collecting pkgutil-resolve-name>=1.3.10
  Using cached pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.19.3-cp38-cp38-win_amd64.whl (62 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Building wheels for collected packages: asoid, hdbscan
  Building wheel for asoid (setup.py) ... done
  Created wheel for asoid: filename=asoid-0.2.0-py3-none-any.whl size=1950556 sha256=4bd9957b2fa58871774e4bd71e39aae9b51faf60bdfb7e3e5b5192500c0a4003
  Stored in directory: c:\users\km195\appdata\local\pip\cache\wheels\5c\a4\05\9c84cdd7c57679cf14ea37eaeb5a5c9ba78cce97f4527639f5
  Building wheel for hdbscan (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hdbscan (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\hdbscan
      copying hdbscan\flat.py -> build\lib.win-amd64-cpython-38\hdbscan
      copying hdbscan\hdbscan_.py -> build\lib.win-amd64-cpython-38\hdbscan
      copying hdbscan\plots.py -> build\lib.win-amd64-cpython-38\hdbscan
      copying hdbscan\prediction.py -> build\lib.win-amd64-cpython-38\hdbscan
      copying hdbscan\robust_single_linkage_.py -> build\lib.win-amd64-cpython-38\hdbscan
      copying hdbscan\validity.py -> build\lib.win-amd64-cpython-38\hdbscan
      copying hdbscan\__init__.py -> build\lib.win-amd64-cpython-38\hdbscan
      creating build\lib.win-amd64-cpython-38\hdbscan\tests
      copying hdbscan\tests\test_flat.py -> build\lib.win-amd64-cpython-38\hdbscan\tests
      copying hdbscan\tests\test_hdbscan.py -> build\lib.win-amd64-cpython-38\hdbscan\tests
      copying hdbscan\tests\test_prediction_utils.py -> build\lib.win-amd64-cpython-38\hdbscan\tests
      copying hdbscan\tests\test_rsl.py -> build\lib.win-amd64-cpython-38\hdbscan\tests
      copying hdbscan\tests\__init__.py -> build\lib.win-amd64-cpython-38\hdbscan\tests
      running build_ext
      cythoning hdbscan/_hdbscan_tree.pyx to hdbscan\_hdbscan_tree.c
      cythoning hdbscan/_hdbscan_linkage.pyx to hdbscan\_hdbscan_linkage.c
      cythoning hdbscan/_hdbscan_boruvka.pyx to hdbscan\_hdbscan_boruvka.c
      cythoning hdbscan/_hdbscan_reachability.pyx to hdbscan\_hdbscan_reachability.c
      cythoning hdbscan/_prediction_utils.pyx to hdbscan\_prediction_utils.c
      cythoning hdbscan/dist_metrics.pyx to hdbscan\dist_metrics.c
      building 'hdbscan._hdbscan_tree' extension
      C:\Users\km195\AppData\Local\Temp\pip-build-env-u7qhkvit\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\km195\AppData\Local\Temp\pip-install-47hnnxp4\hdbscan_fcbebbd4c04b4e65b8090b322e6bb107\hdbscan\_hdbscan_tree.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      C:\Users\km195\AppData\Local\Temp\pip-build-env-u7qhkvit\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\km195\AppData\Local\Temp\pip-install-47hnnxp4\hdbscan_fcbebbd4c04b4e65b8090b322e6bb107\hdbscan\_hdbscan_linkage.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      C:\Users\km195\AppData\Local\Temp\pip-build-env-u7qhkvit\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\km195\AppData\Local\Temp\pip-install-47hnnxp4\hdbscan_fcbebbd4c04b4e65b8090b322e6bb107\hdbscan\_hdbscan_boruvka.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      C:\Users\km195\AppData\Local\Temp\pip-build-env-u7qhkvit\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\km195\AppData\Local\Temp\pip-install-47hnnxp4\hdbscan_fcbebbd4c04b4e65b8090b322e6bb107\hdbscan\_hdbscan_reachability.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      C:\Users\km195\AppData\Local\Temp\pip-build-env-u7qhkvit\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\km195\AppData\Local\Temp\pip-install-47hnnxp4\hdbscan_fcbebbd4c04b4e65b8090b322e6bb107\hdbscan\_prediction_utils.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      C:\Users\km195\AppData\Local\Temp\pip-build-env-u7qhkvit\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\km195\AppData\Local\Temp\pip-install-47hnnxp4\hdbscan_fcbebbd4c04b4e65b8090b322e6bb107\hdbscan\dist_metrics.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hdbscan
Successfully built asoid
Failed to build hdbscan
ERROR: Could not build wheels for hdbscan, which is required to install pyproject.toml-based projects

-------

(asoid) PS C:\Apps\A-SOID> asoid app
asoid : The term 'asoid' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ asoid app
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (asoid:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by JensBlack** [comment]
closing because it seems solved. please reopen if not.
