### ISSUE TITLE
video alignment during refine behavior 

### ISSUE THREAD

**Issue by koosjedr** [YttriLab/A-SOID#90]
When I upload video's to refine behavior my videos are for example 1.0 second long, however the table where I add the behavior per time stamp goes until 2.4. Does this mean that the timestamps in the video are incorrect or that I can discard the rest of the behavior given in the table. 

It is true that the videos I put in the config are 25fps and the videos I want to train the model with are fps 30. 

<img width="1120" alt="Scherm­afbeelding 2024-06-13 om 14 52 02" src="https://github.com/YttriLab/A-SOID/assets/164341083/0e8a5204-c6ee-4e46-9e83-4eaeaaffd0cb">

**Desktop (please complete the following information):**
- Mac M1, Sonoma 14.1.1
- Safari

**Project Config (please post the content of the corresponding config.ini file)**
<img width="1093" alt="Scherm­afbeelding 2024-06-13 om 14 53 01" src="https://github.com/YttriLab/A-SOID/assets/164341083/b39e5955-7add-4134-9c8e-b577af693850">

**Additional context**

**Comment by JensBlack** [comment]
HI @koosjedr ,

so far, we assume that the videos are of the same framerate and do not calculate it again. Can you try a downsampled version and report back?

> Another hacky way (not in general recommended though!) could be to change the fps parameter in the config and then run refinement on those videos.
