### ISSUE TITLE
AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by DavidBarriere** [YttriLab/A-SOID#93]
Dear all,
I get this error while trying to upload DLC csv files :

AxiosError: Request failed with status code 403

Could you help me to fix it please ? 

Thanks

**Comment by JensBlack** [comment]
Hi,

i will need more information than that. Please use the issue template and include the necessary information.

Thanks!

**Comment by DavidBarriere** [comment]
I managed to solve the problem by updating a few libraries.

**Comment by JensBlack** [comment]
@DavidBarriere  Great that you managed to fix it.
It would be great if you could add some additional detail, so other users can benefit from your solution.
