### ISSUE TITLE
StreamlitAPIException: Unrecognized config option: deprecation.showPyplotGlobalUse

### ISSUE THREAD

**Issue by vic7538** [YttriLab/A-SOID#95]
**StreamlitAPIException: Unrecognized config option: deprecation.showPyplotGlobalUse**
Hello,
When I finished installation and start to run with asoid app this error information out. I already downgrading to streamlit v1.31.1 but it still not working. Thanks.
A-SOID-0.3.1
![1](https://github.com/user-attachments/assets/d9bcfb8c-6d1f-4300-8f7e-d92f2bb8d3ec)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Project Config (please post the content of the corresponding config.ini file)**

**Additional context**

**Comment by amorsi1** [comment]
I am encountering the same issue now. Followed standard installation instructions and received this exact same error on both linux and mac systems. 

Looking online on streamlit forums, I do not see others experiecing the same issues.

@vic7538 were you able to resolve this bug?
