### ISSUE TITLE
Initial samples to train per class: grooming [0.0]; immobility [0.0]; licking [0.0]; rearing [0.0]; walking [0.0]

### ISSUE THREAD

**Issue by vic7538** [YttriLab/A-SOID#96]
**Describe the bug**
Hello,
I dont konw what happen to the code. Previously, it work very well.  Now when I upload new data or use old data. All the classes is [0.0]
![2](https://github.com/user-attachments/assets/3b89b8ca-627c-4404-9824-373eb83daced)
version A-SOID-0.3.1

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [Microsoft Edge]

**Project Config (please post the content of the corresponding config.ini file)**
[Project]
PROJECT_TYPE = DeepLabCut
PROJECT_NAME = Jul-29-2024
PROJECT_PATH = C:\Users\N713\Desktop\a-soid\asoid_output
FRAMERATE = 20
KEYPOINTS_CHOSEN = nose, leftear, rightear, neck, body, frontlimbleft, hindlimbleft, frontlimbright, hindlimbright, tailbase, tailmiddle, tailend
EXCLUDE_OTHER = True
FILE_TYPE = csv
INDIVIDUALS_CHOSEN = single animal
CLASSES = grooming, immobility, licking, rearing, walking, other
MULTI_ANIMAL = False
IS_3D = False

[Data]
DATA_INPUT_FILES = basal 14976-1_data.csv, basal 14976-2_data.csv, basal 14976-3_data.csv, basal 14976-4_data.csv, basal 14976-5_data.csv, formalin 1min 14976-1_data.csv, formalin 1min 14976-2_data.csv, formalin 1min 14976-3_data.csv, formalin 1min 14976-4_data.csv, formalin 1min 14976-5_data.csv, formalin 2h 14976-1_data.csv, formalin 2h 14976-2_data.csv, formalin 2h 14976-3_data.csv, formalin 2h 14976-4_data.csv, formalin 2h 14976-5_data.csv, formalin 3d 14976-1_data.csv, formalin 3d 14976-2_data.csv, formalin 3d 14976-3_data.csv, formalin 3d 14976-4_data.csv, formalin 3d 14976-5_data.csv
LABEL_INPUT_FILES = basal 14976-1_No focal subject.csv, basal 14976-2_No focal subject.csv, basal 14976-3_No focal subject.csv, basal 14976-4_No focal subject.csv, basal 14976-5_No focal subject.csv, formalin 1min 14976-1_No focal subject.csv, formalin 1min 14976-2_No focal subject.csv, formalin 1min 14976-3_No focal subject.csv, formalin 1min 14976-4_No focal subject.csv, formalin 1min 14976-5_No focal subject.csv, formalin 2h 14976-1_No focal subject.csv, formalin 2h 14976-2_No focal subject.csv, formalin 2h 14976-3_No focal subject.csv, formalin 2h 14976-4_No focal subject.csv, formalin 2h 14976-5_No focal subject.csv, formalin 3d 14976-1_No focal subject.csv, formalin 3d 14976-2_No focal subject.csv, formalin 3d 14976-3_No focal subject.csv, formalin 3d 14976-4_No focal subject.csv, formalin 3d 14976-5_No focal subject.csv
ROOT_PATH = None

[Processing]
LLH_VALUE = 0.6
ITERATION = 0
MIN_DURATION = 0.1
TRAIN_FRACTION = 0.0
MAX_ITER = 100
MAX_SAMPLES_ITER = 50
CONF_THRESHOLD = 0.5
N_SHUFFLED_SPLIT = None

**Additional context**

**Comment by JensBlack** [comment]
Hi @vic7538,

I will some additional information to help you:

### Did you change any of the code from the asoid-package?
- Is it working if you are installing A-SOiD again (from scratch)?

### Restarting A-SOiD
- Is it working if you are closing the browser and restart A-SOiD?

### Did you alter or delete files from the project you are trying to load?
- Is it working if you are restarting A-SOiD and create a new project instead of loading a preexisting one?

**Comment by vic7538** [comment]
Hi Jens,

Thank you for your response. The issue has been resolved by reinstalling the software, although the process was somewhat tricky. I had to install the original version first and then update it to version 0.3.1 for it to work properly. If I tried installing the latest version directly or using just the original version, it didn’t work.
--
Best regards ,

Wei-Hsin
________________________________
寄件者: Jens Tillmann ***@***.***>
寄件日期: 2024年8月13日 下午 08:50
收件者: YttriLab/A-SOID ***@***.***>
副本: vic7538 ***@***.***>; Mention ***@***.***>
主旨: Re: [YttriLab/A-SOID] Initial samples to train per class: grooming [0.0]; immobility [0.0]; licking [0.0]; rearing [0.0]; walking [0.0] (Issue #96)


Hi @vic7538<https://github.com/vic7538>,

I will some additional information to help you:

Did you change any of the code from the asoid-package?

  *   Is it working if you are installing A-SOiD again (from scratch)?

Restarting A-SOiD

  *   Is it working if you are closing the browser and restart A-SOiD?

Did you alter or delete files from the project you are trying to load?

  *   Is it working if you are restarting A-SOiD and create a new project instead of loading a preexisting one?
