### ISSUE TITLE
Please train a iteration-0 model in Active Learning step

### ISSUE THREAD

**Issue by vic7538** [YttriLab/A-SOID#97]
**Describe the bug**
After the training, I used to predict a new vedio. But, it ask me to go back to learninig step
A-SOID-0.3.1
**To Reproduce**

**Expected behavior**

**Screenshots**
![22](https://github.com/user-attachments/assets/cf7c3f3c-8737-4f73-b02a-9d5946d6a24a)

**Desktop (please complete the following information):**
 OS: [windows]
Browser [Microsoft Edge]

**Project Config (please post the content of the corresponding config.ini file)**
[Project]
PROJECT_TYPE = DeepLabCut
PROJECT_NAME = Aug-02-2024
PROJECT_PATH = C:\Users\N713\Desktop\a-soid\asoid_output
FRAMERATE = 20
KEYPOINTS_CHOSEN = nose, leftear, rightear, neck, body, frontlimbleft, hindlimbleft, frontlimbright, hindlimbright, tailbase, tailmiddle, tailend
EXCLUDE_OTHER = True
FILE_TYPE = csv
INDIVIDUALS_CHOSEN = single animal
CLASSES = grooming, immobility, licking, rearing, walking, other
MULTI_ANIMAL = False
IS_3D = False

[Data]
DATA_INPUT_FILES = basal 14976-1_data.csv, basal 14976-2_data.csv, basal 14976-3_data.csv, basal 14976-4_data.csv, basal 14976-5_data.csv, formalin 1min 14976-1_data.csv, formalin 1min 14976-2_data.csv, formalin 1min 14976-3_data.csv, formalin 1min 14976-4_data.csv, formalin 1min 14976-5_data.csv, formalin 2h 14976-1_data.csv, formalin 2h 14976-2_data.csv, formalin 2h 14976-3_data.csv, formalin 2h 14976-4_data.csv, formalin 2h 14976-5_data.csv, formalin 3d 14976-1_data.csv, formalin 3d 14976-2_data.csv, formalin 3d 14976-3_data.csv, formalin 3d 14976-4_data.csv, formalin 3d 14976-5_data.csv
LABEL_INPUT_FILES = basal 14976-1_No focal subject.csv, basal 14976-2_No focal subject.csv, basal 14976-3_No focal subject.csv, basal 14976-4_No focal subject.csv, basal 14976-5_No focal subject.csv, formalin 1min 14976-1_No focal subject.csv, formalin 1min 14976-2_No focal subject.csv, formalin 1min 14976-3_No focal subject.csv, formalin 1min 14976-4_No focal subject.csv, formalin 1min 14976-5_No focal subject.csv, formalin 2h 14976-1_No focal subject.csv, formalin 2h 14976-2_No focal subject.csv, formalin 2h 14976-3_No focal subject.csv, formalin 2h 14976-4_No focal subject.csv, formalin 2h 14976-5_No focal subject.csv, formalin 3d 14976-1_No focal subject.csv, formalin 3d 14976-2_No focal subject.csv, formalin 3d 14976-3_No focal subject.csv, formalin 3d 14976-4_No focal subject.csv, formalin 3d 14976-5_No focal subject.csv
ROOT_PATH = None

[Processing]
LLH_VALUE = 0.6
ITERATION = 0
MIN_DURATION = 0.1
TRAIN_FRACTION = 0.13
MAX_ITER = 500
MAX_SAMPLES_ITER = 50
CONF_THRESHOLD = 0.5
N_SHUFFLED_SPLIT = None

**Additional context**

**Comment by JensBlack** [comment]
Hi @vic7538,

1. Did you train a model in the active learning step?

- Can you send me a screenshot of the active learning tab please?

2. Did you change or delete any of the files in the project folder?

- Can you send me a screenshot (or list) of the content of the corresponding project folder?

3. Can you try to create the project from scratch again and see if the error reoccurs? 

- This time, please be note if you made any changes from the "standard" route to use A-SOiD.


Thanks!

**Comment by vic7538** [comment]
Hi Jens,

Thank for your reply. This problem has been solved with the reinstalling.

--
Best regards ,

Wei-Hsin
________________________________
寄件者: Jens Tillmann ***@***.***>
寄件日期: 2024年8月14日 下午 03:39
收件者: YttriLab/A-SOID ***@***.***>
副本: vic7538 ***@***.***>; Mention ***@***.***>
主旨: Re: [YttriLab/A-SOID] Please train a iteration-0 model in Active Learning step (Issue #97)


Hi @vic7538<https://github.com/vic7538>,

  1.  Did you train a model in the active learning step?

  *   Can you send me a screenshot of the active learning tab please?

  1.  Did you change or delete any of the files in the project folder?

  *   Can you send me a screenshot (or list) of the content of the corresponding project folder?

  1.  Can you try to create the project from scratch again and see if the error reoccurs?

  *   This time, please be note if you made any changes from the "standard" route to use A-SOiD.

Thanks!

**Comment by JensBlack** [comment]
Great that you found a solution!
