### ISSUE TITLE
StreamlitAPlException: Unrecognized config option: deprecation.showPyplotGlobalUse

### ISSUE THREAD

**Issue by TTX-74** [YttriLab/A-SOID#99]
**Describe the bug**
After installing A-SOID to M3 Macbook Pro and running the asoid app command I get an error in my Safari browser: StreamlitAPlException: Unrecognized config option: deprecation.showPyplotGlobalUse
I downgraded Streamlit but the error remains the same.

**To Reproduce**
Run asoid app command in Terminal and wait for the Safari browser to open url

**Expected behavior**
Load A-SOID app

**Screenshots**
![image](https://github.com/user-attachments/assets/e1844815-c99e-4351-800e-328d25436ddc)

**Desktop (please complete the following information):**
 - OS: MacOS 14.6.1
 - Browser: Safari
 - Version: 17.6

**Project Config (please post the content of the corresponding config.ini file)**

**Additional context**

**Comment by JensBlack** [comment]
Hi, thanks for reporting this. Can you give me more info about the streamlit versions you have used and downgraded to?
Thanks!

**Comment by TTX-74** [comment]
I got the same exact errors with the streamlit version that came with the current A-SOID package and also when I downgraded to v1.31.1.

**Comment by TTX-74** [comment]
Issue fixed with downgraded version of streamlit (1.31.1). Thanks.
